# Copyright IBiiM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt,/var/hyperledger/peercrypto/gda.example.com/peers/peer0.gda.example.com/tls/ca.crt,/var/hyperledger/peercrypto/advocate.example.com/peers/peer0.advocate.example.com/tls/ca.crt,/var/hyperledger/peercrypto/builder.example.com/peers/peer0.builder.example.com/tls/ca.crt,/var/hyperledger/peercrypto/bank.example.com/peers/peer0.bank.example.com/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
    - ../crypto-config/peerOrganizations:/var/hyperledger/peercrypto
    - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.advocate.example.com:
    container_name: peer0.org1.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.advocate.example.com
      - CORE_PEER_ADDRESS=peer0.advocate.example.com:7051
     # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.advocate.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.advocate.example.com:7051
      - CORE_PEER_LOCALMSPID=advocate
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/advocate.example.com/peers/peer0.advocate.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/advocate.example.com/peers/peer0.advocate.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.advocate.example.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer0.gda.example.com:
    container_name: peer0.gda.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.gda.example.com
      - CORE_PEER_ADDRESS=peer0.gda.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.gda.example.com:7051
     # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.gda.example.com:7051
      - CORE_PEER_LOCALMSPID=gda
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/gda.example.com/peers/peer0.gda.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/gda.example.com/peers/peer0.gda.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.gda.example.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053


  peer0.builder.example.com:
    container_name: peer0.builder.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.builder.example.com
      - CORE_PEER_ADDRESS=peer0.builder.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.builder.example.com:7051
     # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.builder.example.com:7051
      - CORE_PEER_LOCALMSPID=builder
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/builder.example.com/peers/peer0.builder.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/builder.example.com/peers/peer0.builder.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.builder.example.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053    


  peer0.bank.example.com:
    container_name: peer0.bank.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.bank.example.com
      - CORE_PEER_ADDRESS=peer0.bank.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bank.example.com:7051
     # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.bank.example.com:7051
      - CORE_PEER_LOCALMSPID=bank
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/bank.example.com/peers/peer0.bank.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/bank.example.com/peers/peer0.bank.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.bank.example.com:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053      
